### PR TITLE
Add basic windows support

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR adds a patch to have conda insert the correct absolute path of the python interpreter at install time into each of the scripts. Without this patch, if users don't activate the environment, this would select the wrong python interpreter at runtime potentially leading to confusing errors.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@jrollins, please review this and merge if you're happy.

**Comment by jrollins** [comment]
> @jrollins, please review this and merge if you're happy.
> 
> For the record, `/opt/anaconda1anaconda2anaconda3` is a placeholder that `conda` and `conda-build` understand and replace with the relevant environment prefix at install time.

@duncanmmacleod would it be easier to just patch guardian to use entry_points and drop the separate shell invocation scripts?  I've seen load performance issue with the entry_point generated scripts, but I think they're probably fine for the purposes of conda.

**Comment by duncanmmacleod** [comment]
> > @jrollins, please review this and merge if you're happy.
> > For the record, `/opt/anaconda1anaconda2anaconda3` is a placeholder that `conda` and `conda-build` understand and replace with the relevant environment prefix at install time.
> 
> @duncanmmacleod would it be easier to just patch guardian to use entry_points and drop the separate shell invocation scripts? I've seen load performance issue with the entry_point generated scripts, but I think they're probably fine for the purposes of conda.

Yes, it would, and cleaner too, I think. If you meant to write '_loads of performance issues_', then yes, I think is it well documented that setuptools-created entry points take ages to boot. Conda does not use setuptools for entry points, so there should be no associated performance issues. I will make that change for everything except `guardlog` - which I think still needs something like this patch because of the extra handling.

**Comment by jrollins** [comment]
I did actually mean "load performance", meaning that the setuptools load at script invocation would make the scripts very slow to start.  But if that's not used in conda then that's great.

**Comment by duncanmmacleod** [comment]
@jrollins, I have updated the patch(es) to convert most of the scripts to entry points, and to just exclude `guardlog` from windows - which in turn enables a windows version of the package. It doesn't work, but it probably was never going to, but it builds at least, which is something.

**Pull request merged**
